### PR TITLE
fix issue #149 - add .js to esm modules

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
so the elements could be used in https://node-projects.github.io/web-component-designer-demo/index.html

**Comment by urish** [comment]
Thanks. Could the @node-projects/add-js-to-esm-modules be modified to produce less output? right now it's very chatty. Ideally it'd produce no output, or just a summary with the number of files/import statements modified and the run time.

Also, is it possible to add some unit tests to the source code of that module? To ensure that future version won't cause regressions that will possibly break the build of packages using it.

**Comment by jogibear9988** [comment]
will do some tests and be less chatty 😉
but will do it next week.

**Comment by urish** [comment]
@GervinFung congrats on your projects! This is not really a priority for me now, but I'll keep it in mind.

**Pull request closed without merging**
