### PR TITLE
Remove usage of depracated KeyboardEvent.keyCode

### LINKED ISSUE #44: Remove usage of depracated KeyboardEvent.keyCode
The following components use `KeyboardEvent.keyCode`, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode): 

* [pushbutton-element](https://github.com/wokwi/wokwi-elements/blob/f698e0c8ee39debcfaf6b59f5508cdb05d786c92/src/pushbutton-element.ts#L49)
* [membrane-keypad-element](https://github.com/wokwi/wokwi-elements/blob/f698e0c8ee39debcfaf6b59f5508cdb05d786c92/src/membrane-keypad-element.ts#L84)

We can switch to [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) or [`KeyboardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead.

### PR DESCRIPTION
**Pull request by takuma-watanabe**
This PR resolve #44 .

### CODE REVIEW

**Comment by urish** [comment]
First of all, thank you! 

I'm thinking it might make even more sense to move the `SPACE_KEYS` array into a common file (e.g. `src/utils/keys.ts` or something similar), instead of redefining it in each element that needs it. WDYT?

**Comment by takuma-watanabe** [comment]
Thanks for your review!
I will try to move `SPACE_KEYS` array to common file.

**Comment by takuma-watanabe** [comment]
@urish I fixed. Please review again.

**Comment by sutaburosu** [comment]
@takuma-watanabe there's also `triggerKeys` in the Nano element that could be adapted to use `utils\keys.ts`.  I included `Enter` in that list because I found pressing Space could also scroll the window in some circumstances.

**Comment by urish** [comment]
good point @sutaburosu, I'd love to see this in a subsequent PR

**Comment by sutaburosu** [comment]
I'll do that now. :)

**Comment by takuma-watanabe** [comment]
@sutaburosu I couldn't notice that point. Thank you.

**Pull request merged**
